### ISSUE TITLE
Compilation problem: missing ESP.h

### ISSUE THREAD

**Issue by RanTalbott** [romkey/ESP-Diagnostic-Tool#1] opened 2019-03-03 13:22 UTC
Ubuntu 16.04, Arduino IDE 1.8.4 already installed
Installed platformio CLI with pip install -U platformio
(Side note: the install instructions were incomplete, and misleading. platformio came up "Command not found". I had to chase down the software directory, which turned out to be ~/.local/bin and add it to my PATH)

Compilation failed because it couldn't find ESP.h. The error message suggested using platformio search tools to find it, but it's not a platformio file. Those tools came up empty.

I found Esp.h in the Arduino tree at:
 .arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/Esp.h
and
.arduino15/packages/esp32/hardware/esp32/1.0.1/cores/esp32/Esp.h

Since I'm testing ESP8266s, I copied the first one to the src directory, and changed esp8266.cpp and esp32.cpp to
#include "Esp.h"

I had to change both because platformio compiles both, even though I specified the board type as d1_mini

Since the two header files are different, this kluge might cause bad code generation if compiled for ESP32

Note the case change on the header file name: perhaps platformio is different, but I've had problems with Arduino packages that relied on Windoze filenames being case-insensitive. So I changed it to be safe.

After the above, everything worked fine.

Thanks for sharing this: one of the D1 Minis I just bought came with a bad WiFi section, and this tool was able to identify that as the reason that the software (which had been working fine on another D1 mini) kept crashing.

Remembering the WiFi credentials is a nice touch: I got a pleasant surprise when I plugged a mini back in, and it connected itself. I though I was going to have to enter the info again.

Another good test to add might be a version of Arduino's TelnetClient. It could be used to send data back and forth across WiFi for an extended period as a "burn-in" test. A Python program on the PC would alternate between the telnet socket and the serial port, making sure that what it sent on one was properly received on the other. Would that be small enough to fit in ESP memory (I saw the note about dropping Bluetooth)?

**Comment by romkey** [comment] 2019-03-08 00:48
Thank you very much for reporting this!

I was mystified at first and then I realized the problem is because I primarily develop on a Mac with a case-insensitive filesystem. So ESP.h worked on my Mac and I hadn't noticed that I'd gotten the case wrong. Sorry for the problem that caused you - I'm glad you got it working. This should be fixed now. I'll try to remember to run some test builds under Linux in the future to catch this kind of mistake.

I also updated esp8266.cpp and esp32.cpp to wrap the entire files with conditional compile statements for their platforms, so there should be no need to copy Esp.h into the build directory anymore.

I'm glad to hear this helped you identify the bad D1.

Remembering the wifi credentials is something the Arduino SDK does - it's handy sometimes but it can also be very confusing to people who don't understand why their ESP8266 is connecting to wifi when they didn't configure it to. There's a barely documented call, `WiFi.persistent()` which controls this.

That's a great suggestion. I'm sure that could fit. I have quite a few other things I'd like to add to the code; I'll add that to the list.

Thanks!

**Closed as completed by romkey** 2019-03-08 00:48 UTC
